[phases.setup]
aptPkgs = ['python3', 'python3-pip', 'python3-venv']

[phases.install]
cmds = [
  'python -m venv /opt/venv',
  '. /opt/venv/bin/activate && pip install --no-cache-dir -r requirements.txt',
  'apt-get clean && rm -rf /var/lib/apt/lists/*'
]

[start]
cmd = '. /opt/venv/bin/activate && gunicorn run:app --bind 0.0.0.0:$PORT'