# nixpacks.toml
[phases.setup]
# Use Nix’s Python interpreter and pip directly
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
# Install your Python dependencies without caching wheels
cmds = [
  "pip install --no-cache-dir -r requirements.txt"
]

[start]
# Use Gunicorn (faster, production‑ready) to serve your app
# Adjust `run:app` to point at your Flask app object
cmd = "gunicorn run:app --bind 0.0.0.0:$PORT"
