[phases.setup]
aptPkgs = ['python3-dev', 'python3-pip', 'python3-venv']

[phases.install]
cmds = [
  'python -m venv /opt/venv',
  '. /opt/venv/bin/activate && pip install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cpu',
  '. /opt/venv/bin/activate && pip install --no-cache-dir -r requirements.txt',
  'find /opt/venv -name "*.pyc" -delete',
  'find /opt/venv -name "__pycache__" -type d -exec rm -rf {} +',
  'apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*'
]

[start]
cmd = '. /opt/venv/bin/activate && gunicorn run:app --bind 0.0.0.0:$PORT'